### ISSUE TITLE
Syntax error with latest commit

### ISSUE THREAD

**Issue by noaho** [rhansen/unlock-cryptroot#3]
Since the latest commit, I get:

    line 151: syntax error near unexpected token `;;'

and

    line 151: `    case $2 in remove) fatal "'cryptsetup remove' is running";; esac'

Thanks for still working on the script btw, I appreciate it 👍

**Comment by rhansen** [comment]
There's no syntax error there that I can see.  What is the output of `/bin/sh --version`?

**Comment by noaho** [comment]
Sorry, I'm trying from OS X 10.12.6, could that be the issue?

```
/bin/sh --version                                                                                                                                                      
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

```
./unlock-cryptroot -i ~/files/ServerHost/id_rsa ServerHost                                                                                                   
./unlock-cryptroot: line 151: syntax error near unexpected token `;;'
./unlock-cryptroot: line 151: `    case $2 in remove) fatal "'cryptsetup remove' is running";; esac'
```

**Comment by espoelstra** [comment]
Can you try installing `shellcheck` and then run `shellcheck unlock-cryptroot` or if you have Docker installed try the command below from wherever you checked out the project?

```
docker run --rm -i -t \
		--name df-shellcheck \
		-v $(pwd):/usr/src:ro \
		--workdir /usr/src \
    --entrypoint shellcheck
		r.j3ss.co/shellcheck unlock-cryptroot
```

**Comment by noaho** [comment]
I think it was because I was running zsh, sorry about this.
